import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Link from "next/link";
import SignOut from "../components/Auth/SignOut";
import SignIn from "../components/Auth/SignIn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href="/">Home</Link> | <Link href="/all-books">All Books</Link>
          {session ? <SignOut /> : <SignIn />}
          {session && <span>Welcome back: {session.user?.name}</span>}
        </header>
        {children}
      </body>
    </html>
  );
}
